# Generated by Django 2.0.1 on 2018-01-31 21:28

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
