# Generated by Django 2.0.1 on 2018-02-03 13:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180131_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
