# Generated by Django 2.0.1 on 2018-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180203_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('menu_position',)},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='ordering',
            new_name='menu_position',
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
    ]
