# Generated by Django 2.0.1 on 2018-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180203_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
