# Generated by Django 2.0.1 on 2018-02-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180204_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_scripts',
            new_name='page_head',
        ),
    ]
